# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1psrjY02e41cNMVmovgxz7huQ3faCb5ni
"""

import streamlit as st
import joblib

# Cargar el modelo
model = joblib.load(r'C:\Users\ivana\Desktop\Maestría en ing\primer semestre\Machine learning\housing_app\\lin_reg_model.joblib')

# Título de la aplicación
st.title('Predicción de Precios de Viviendas en California')

# Entradas de usuario
med_inc = st.slider('Ingreso Medio', 0.0, 15.0, 1.0)
house_age = st.slider('Edad de la Vivienda (años)', 0, 100, 10)
ave_rooms = st.slider('Promedio de Habitaciones', 1, 10, 3)
ave_bedrms = st.slider('Promedio de Dormitorios', 1, 5, 2)
population = st.slider('Población', 0, 100000, 1000)
ave_occup = st.slider('Promedio de Ocupación', 1, 10, 3)
latitude = st.slider('Latitud', 32.0, 42.0, 36.0)
longitude = st.slider('Longitud', -124.0, -114.0, -118.0)

# Realizar la predicción
prediction = model.predict([[med_inc, house_age, ave_rooms, ave_bedrms, population, ave_occup, latitude, longitude]])

# Mostrar la predicción
st.write(f'**Predicción del Precio de la Vivienda:** ${prediction[0]:,.2f}')